language: node_js
node_js:
- '0.10'
services:
- neo4j
before_script:
- npm install -g grunt-cli
addons:
  sauce_connect: true
deploy:
  provider: heroku
  app: movie-database-node
  api_key:
    secure: LfX4hB0xQv9z4ZD+Iiz0tffiNceHyB4/wfeFacra7m9xLpjtpqOmBvbQGzl3 3EGek2clup/ri2RHHQm5QCqK5L8ohptvHSoBusghHmXyV80knIb8mlnpmwMe
      7Vs7v9wdALHudWPHly9pN0OZHxYsRprQc8R6b2rowAdMxzMraDg=
env:
  global:
  - secure: iFnTOv+kOrBUai/KItEBbAM6WRXV08WSBbE9aJWfO4H7fh3vj9uMO04j+uvlSEbJJSZntbU/nEtJOF/2IHTSyVMCLFP+heNpXhlL0IzFEwWQUQf4dF6Nb+h14UYH6H5eLmCJZG3TktxT3MfChOu+/iIJ3E7HJdS4sXCmgx4K0dI=
  - secure: SvGTIJ7qj7GAsaV8r1CMTanHOWqV8vufrLvzfEAUPHHYPaaWvIaaP+G4apk60jHYivdU0TY2SfYeu6cs5AUJK7gbBBOet1g5ed2YZCs/MHeLtSs5/wp9lpxvF/d4yd3LIwiQkKndgh7CAxualblU72MMabl1vLn6HxJArQb2ty0=
